---
sidebar: sidebar 
permalink: reference-local-known-limitations.html 
keywords: console local deployment, known limitations, unsupported platforms, unsupported devices, unsupported functions, IP range 
summary: NetApp Console 로컬 배포 시 알려진 제한 사항에 대한 참조 자료입니다. 
---
= NetApp Console 로컬 배포의 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원되지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 나타냅니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



[[console-vm-limitations]]
== 콘솔 VM 제한 사항



[[possible-conflict-with-ip-addresses-in-the-10-42-0-016-and-10-43-0-016-ranges]]
=== 10.42.0.0/16 및 10.43.0.0/16 범위의 IP 주소와 충돌 가능성

NetApp Console 로컬 배포는 서비스 간 통신을 위해 고정 주소 공간을 사용합니다. 내부 네트워크에는 10.42.0.0/16 및 10.43.0.0/16 IP 범위가 사용됩니다. Console 로컬 배포를 설치하기 전에 Console 로컬 배포에 할당된 VLAN에서 이러한 IP 범위가 다른 VM, DHCP 범위, DNS 레코드 또는 로드 밸런서 VIP 풀에 할당되지 않았는지 확인하십시오.

에이전트 인터페이스의 IP 주소를 변경하는 방법에 대한 지침은 기술 자료 문서 "Agent IP conflict with existing network"를 참조하십시오.



[[shared-linux-hosts-are-not-supported]]
=== 공유 Linux 호스트는 지원되지 않습니다

NetApp Console 로컬 배포는 다른 애플리케이션과 공유되는 VM에서는 지원되지 않습니다. VM은 NetApp Console 로컬 배포 전용이어야 합니다.



[[third-party-agents-and-extensions]]
=== 타사 에이전트 및 확장 기능

타사 에이전트 또는 VM 확장 기능은 NetApp Console 로컬 배포 VM에서 지원되지 않습니다.



[[identity-and-access-limitations]]
== 신원 및 접근 제한

[cols="1,3"]
|===
| 영역 | 제한 사항 


| 로컬 사용자 온보딩 및 계정 복구 | 로컬 사용자를 초대하거나 로컬 사용자의 비밀번호 재설정을 사용하려면 먼저 SMTP 이메일 서버를 구성해야 합니다. 


| Active Directory 통합 | 로컬 사용자와 Active Directory 사용자 간에 동일한 이메일 주소를 사용할 수 없습니다. 예를 들어, 최초 로컬 조직 관리자가 나중에 Active Directory 사용자로 자신을 추가하는 경우 다른 이메일 주소를 사용해야 합니다. 
|===