---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, Organization admin, Folder or fleet admin, Super admin, Federation admin, platform roles, role, iam, identity and access management, netapp console local 
summary: 플랫폼 역할을 사용자에게 할당하여 NetApp Console 로컬 배포 관리, 역할 할당, 사용자 추가 및 페더레이션 관리 권한을 부여할 수 있습니다. 
---
= NetApp Console 로컬 배포 플랫폼 액세스 역할
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
플랫폼 역할을 사용자에게 할당하여 NetApp Console 로컬 배포 관리, 역할 할당, 사용자 추가, 플릿 생성 및 사용자 인증 관리 권한을 부여합니다.

.대규모 다국적 기업의 조직 역할 예시
XYZ Corporation은 데이터 스토리지 액세스를 북미, 유럽, 아시아 태평양 등 지역별로 구성하여 중앙 집중식 감독 하에 지역별 제어가 가능하도록 합니다.

XYZ Corporation의 Console 로컬 배포 환경에서 *조직 관리자*는 초기 조직과 각 지역별 폴더를 생성합니다. 각 지역의 *폴더 또는 플리트 관리자*는 해당 지역 폴더 내에서 플리트(및 관련 리소스)를 구성합니다.

*폴더 또는 플릿 관리자* 역할을 가진 지역 관리자는 리소스와 사용자를 추가하여 해당 폴더를 적극적으로 관리합니다. 이러한 지역 관리자는 자신이 관리하는 폴더와 플릿을 추가, 삭제 또는 이름을 변경할 수도 있습니다. *조직 관리자*는 새로 추가된 리소스에 대한 권한을 상속받아 조직 전체의 스토리지 사용량을 파악할 수 있습니다.

같은 조직 내에서 한 사용자에게 *Federation admin* 역할이 부여되어 해당 조직과 회사 IdP 간의 페더레이션을 관리합니다. 이 사용자는 페더레이션된 조직을 추가하거나 제거할 수 있지만, 조직 내의 사용자나 리소스를 관리할 수는 없습니다. *Organization admin*은 페더레이션 상태를 확인하고 페더레이션된 조직을 볼 수 있도록 *Federation viewer* 역할을 사용자에게 부여합니다.

다음 표는 각 Console 로컬 배포 플랫폼 역할이 수행할 수 있는 작업을 나타냅니다.



[[organization-administration-roles]]
[[organization-admin-roles]]
== 조직 관리 역할

[cols="2,1,1"]
|===
| 작업 | 조직 관리자 | 폴더 또는 플릿 관리자 


| 콘솔 로컬 배포에서 시스템을 생성, 수정 또는 삭제합니다(시스템 추가 또는 검색). | 예 | 예 


| 폴더 및 플릿 생성, 삭제 포함 | 예 | 아니요 


| 기존 폴더 및 플릿의 이름 변경 | 예 | 예 


| 역할 할당 및 사용자 추가 | 예 | 예 


| 리소스를 폴더 및 플릿과 연결합니다. | 예 | 예 


| Console을 통해 지원을 등록하고 케이스를 제출합니다. | 예 | 예 


| 명시적인 액세스 역할과 연결되지 않은 데이터 서비스를 사용합니다. | 예 | 예 


| 감사 페이지 및 알림 보기 | 예 | 예 
|===


[[federation-roles]]
== 페더레이션 역할

[cols="2,1,1"]
|===
| 작업 | Federation 관리자 | 페더레이션 뷰어 


| 디렉터리 서비스 통합 생성 및 업데이트 | 예 | 아니요 


| 페더레이션 및 세부 정보 보기 | 예 | 예 
|===


[[super-admin-and-viewer-roles]]
[[super-admin-roles]]
== 최고 관리자 및 뷰어 역할

*Super admin* 역할은 Console 기능, 스토리지 및 데이터 서비스를 관리할 수 있는 모든 권한을 제공합니다. 이 역할은 관리 및 거버넌스를 총괄하는 담당자에게 적합합니다. 반면, *Super viewer* 역할은 읽기 전용 권한을 제공하며, 변경 없이 현황을 파악해야 하는 감사자 또는 이해관계자에게 적합합니다.

조직은 보안 위험을 최소화하고 최소 권한 원칙을 준수하기 위해 *슈퍼 관리자* 액세스 권한을 신중하게 사용해야 합니다. 대부분의 조직은 위험을 줄이고 감사 가능성을 높이기 위해 필요한 권한만 부여하는 세분화된 역할을 할당해야 합니다.

.슈퍼 역할의 예시
ABC Corporation은 데이터 서비스 및 스토리지 관리를 위해 NetApp Console을 활용하는 5명으로 구성된 소규모 팀을 운영하고 있습니다. 여러 역할을 분담하는 대신, 사용자 관리 및 리소스 구성을 포함한 모든 관리 작업을 담당하는 두 명의 선임 팀원에게 *Super admin* 역할을 부여합니다. 나머지 세 명의 팀원에게는 *Super viewer* 역할이 부여되어 설정을 수정하는 기능 없이 스토리지 상태 및 데이터 서비스 상태를 모니터링할 수 있습니다.

[cols="2,1"]
|===
| 역할 | 상속된 역할 


 a| 
최고 관리자
 a| 
* 조직 관리자
* 폴더 또는 플릿 관리자
* 백업 및 복구 최고 관리자
* 스토리지 관리자




 a| 
슈퍼 뷰어
 a| 
* 조직 뷰어
* 백업 뷰어
* 스토리지 뷰어


|===