---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, open ticket, web ticket, open an issue 
summary: 'NetApp은 다양한 방식으로 NetApp Console 로컬 배포를 지원합니다. 기술 자료(KB) 문서 및 커뮤니티 포럼 등 광범위한 무료 자가 지원 옵션을 연중무휴 24시간 이용할 수 있습니다. 지원 등록에는 웹 티켓팅을 통한 원격 기술 지원이 포함됩니다.' 
---
= NetApp Console 로컬 배포 관련 도움말
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp은 다양한 방식으로 NetApp Console 로컬 배포를 지원합니다. 기술 자료(KB) 문서 및 커뮤니티 포럼 등 광범위한 무료 자가 지원 옵션을 연중무휴 24시간 이용할 수 있습니다. NetApp Console 로컬 배포와 연결된 스토리지 리소스의 일련 번호를 사용하여 지원을 등록할 수 있습니다. 등록에는 웹 티켓팅을 통한 원격 기술 지원이 포함됩니다.



[[use-self-support-options]]
== 셀프 지원 옵션 사용

이러한 옵션은 연중무휴 24시간 무료로 이용할 수 있습니다.

* 설명서
+
현재 보고 계신 NetApp Console 로컬 배포 문서입니다.

* https://kb.netapp.com/Cloud/BlueXP["지식 기반"^]
+
NetApp 기술 자료에서 문제 해결에 도움이 되는 문서를 검색하십시오.





[[open-a-support-case-with-netapp-console-local-deployment]]
== NetApp Console 로컬 배포로 지원 사례 열기

NetApp Console 로컬 배포 환경에서 관리되는 NetApp 스토리지 시스템 일련 번호 중 하나를 사용하여 지원 사례를 개설하십시오.

.단계
.  https://mysupport.netapp.com["NetApp 지원 사이트"^]로 이동하여 NetApp 지원 계정으로 로그인하십시오.
. *Cases and Parts > Create Technical Case*를 선택하십시오.
. 문제가 발생한 Console 로컬 배포 제품과 연결된 NetApp 스토리지 시스템의 일련 번호를 입력하십시오.
. 새 케이스를 생성하고 NetApp Console 로컬 배포에 적합한 카테고리 코드를 선택하십시오.




[[download-a-support-bundle]]
== 지원 번들을 다운로드합니다

지원 패키지에는 최근 로그 및 구성 정보가 포함되어 있습니다. 최신 패키지를 다운로드하여 요청 시 NetApp 기술 지원팀에 보낼 수 있습니다.

.단계
. 지원 페이지를 보려면 *관리 > 지원*을 선택하십시오.
. 지원 카드에서 *생성*을 선택하여 로그 및 구성 데이터 묶음을 생성합니다.
. 번들 생성이 완료되면 *다운로드*를 선택합니다. ZIP 파일을 다운로드하라는 메시지가 표시됩니다.
+
이 시스템은 한 번에 하나의 지원 번들만 유지합니다. 새 지원 번들을 생성하면 이전 번들이 대체됩니다.


