---
sidebar: sidebar 
permalink: task-console-local-vm-config.html 
keywords: Console local VM, vcenter, esxi, increase cpu, increase ram, vm maintenance, Console local maintenance, Console local operating system, Console local host 
summary: 콘솔 로컬 배포를 완료한 후 기존 vCenter 또는 ESXi 호스트를 변경할 수 있습니다. 예를 들어 콘솔 로컬 배포를 호스팅하는 VM 인스턴스의 CPU 또는 RAM을 늘릴 수 있습니다. 
---
= NetApp Console 로컬 배포를 위해 vCenter 또는 ESXi 호스트를 유지 관리하십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 로컬 배포를 사용하면 콘솔 로컬 배포를 배포한 후 기존 vCenter 또는 ESXi 호스트를 변경할 수 있습니다. 예를 들어 콘솔 로컬 배포를 호스팅하는 VM 인스턴스의 CPU 또는 RAM을 늘릴 수 있습니다.

VM 웹 콘솔을 사용하여 다음 유지 관리 작업을 수행하십시오.

* 디스크 크기 늘리기
* 콘솔 로컬 배포를 다시 시작합니다
* 정적 경로 업데이트
* 검색 도메인 업데이트


.제한 사항
유지 관리 콘솔을 통해서는 IP 주소, DNS 및 게이트웨이에 대한 정보를 보기만 할 수 있으며 업데이트는 불가능합니다.



[[access-the-vm-maintenance-console]]
== VM 유지 관리 콘솔에 액세스합니다.

VSphere 클라이언트를 통해 유지 관리 콘솔에 액세스할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.




[[change-the-maint-user-password]]
=== maint 사용자 암호를 변경합니다

 `maint` 사용자의 비밀번호를 변경할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.
. 를 입력하여 `1` `System Configuration` 메뉴를 봅니다.
. Enter `1`를 입력하여 유지보수 사용자 암호를 변경하고 화면의 안내에 따라 진행하십시오.




[[increase-the-cpu-or-ram-of-the-vm-instance]]
=== 가상 머신 인스턴스의 CPU 또는 RAM을 늘립니다.

콘솔 로컬 배포를 호스팅하는 VM 인스턴스의 CPU 또는 RAM을 늘릴 수 있습니다.

VCenter 또는 ESXi 호스트에서 VM 인스턴스 설정을 편집한 다음 유지 관리 콘솔을 사용하여 변경 사항을 적용하십시오.

.VSphere 클라이언트에서의 단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. VM 인스턴스를 마우스 오른쪽 버튼으로 클릭하고 *설정 편집*을 선택합니다.
. /opt 또는 /var 파티션에 사용되는 하드 드라이브 공간을 늘리십시오.
+
.. /opt에 사용되는 하드 드라이브 공간을 늘리려면 *하드 디스크 2*를 선택하십시오.
.. /var에 사용되는 하드 드라이브 공간을 늘리려면 *하드 디스크 3*을 선택하십시오.


. 변경 사항을 저장합니다.


.유지보수 콘솔에서의 단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.
. Enter `1 to view the `System Configuration` 메뉴를 입력하세요.
. 입력  `2`후 화면의 안내에 따라 진행하십시오. 콘솔이 새 설정을 검색하고 파티션 크기를 늘립니다.




[[view-network-settings-for-the-console-local-deployment-vm]]
=== 콘솔 로컬 배포 VM의 네트워크 설정 보기

vSphere 클라이언트에서 콘솔 로컬 배포 VM의 네트워크 설정을 확인하여 네트워크 문제를 점검하거나 해결할 수 있습니다. 다음 네트워크 설정은 확인만 가능하며 업데이트는 불가능합니다. IP 주소 및 DNS 세부 정보.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.
.  `2`을 입력하여  `Network Configuration` 메뉴를 봅니다.
. 1에서 6 사이의 숫자를 입력하여 해당 네트워크 설정을 확인하십시오.




[[update-the-static-routes-for-the-console-local-deployment-vm]]
=== 콘솔 로컬 배포 VM의 정적 경로를 업데이트합니다.

필요에 따라 콘솔 로컬 배포 VM에 대한 정적 경로를 추가, 업데이트 또는 제거합니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.
.  `2`을 입력하여  `Network Configuration` 메뉴를 봅니다.
. 정적 경로를 업데이트하려면  `7`을 입력하고 화면의 안내에 따라 진행하십시오.
. Enter 키를 누릅니다.
. 필요에 따라 추가적인 변경을 할 수 있습니다.
. 변경 사항을 커밋하려면  `9`을 누르십시오.




[[update-domain-search-settings-for-the-console-local-deployment-vm]]
=== 콘솔 로컬 배포 VM의 도메인 검색 설정 업데이트

콘솔 로컬 배포 VM의 검색 도메인 설정을 업데이트할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.
. 를 입력하여 `2`` `Network Configuration` 메뉴를 봅니다.
.  `8`을 입력하여 도메인 검색 설정을 업데이트하고 화면의 안내에 따라 진행하십시오.
. Enter 키를 누릅니다.
. 필요에 따라 추가적인 변경을 할 수 있습니다.
. 변경 사항을 커밋하려면  `9`을 누르십시오.




[[access-the-console-local-deployment-diagnostic-tools]]
[[connect-vcenter-host]]
=== 콘솔 로컬 배포 진단 툴에 액세스합니다

Console 로컬 배포 관련 문제를 해결하기 위해 진단 툴에 액세스합니다. NetApp 지원팀에서 문제 해결 시 이 작업을 요청할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.
. 지원 및 진단 메뉴를 보려면  `3`을 입력하십시오.
.  `1`을 입력하여 진단 툴에 액세스하고 화면의 안내에 따라 진행하십시오.




[[access-the-console-local-deployment-diagnostic-tools-remotely]]
=== 콘솔 로컬 배포 진단 툴에 원격으로 액세스합니다.

Putty 등의 툴을 사용하여 원격으로 진단 툴에 액세스할 수 있습니다. 일회용 암호를 할당하여 Console 로컬 배포 VM에 대한 SSH 액세스를 활성화하십시오.

SSH 접속을 통해 복사 및 붙여넣기와 같은 고급 터미널 기능을 사용할 수 있습니다.

.단계
. VSphere 클라이언트를 열고 VCenter에 로그인합니다.
. 콘솔 로컬 배포를 호스팅하는 VM 인스턴스를 선택하십시오.
. *웹 콘솔 실행*을 선택합니다.
. 가상 머신 인스턴스를 생성할 때 지정한 사용자 이름과 암호를 사용하여 가상 머신 인스턴스에 로그인하십시오. 사용자 이름은  `maint`이고 암호는 가상 머신 인스턴스를 생성할 때 지정한 것입니다.
.  `3`을 입력하여  `Support and Diagnostics` 메뉴를 봅니다.
.  `2`을 입력하여 진단 툴에 액세스하고 화면의 안내에 따라 24시간 후에 만료되는 일회용 비밀번호를 구성하십시오.
. Putty 등 SSH 툴을 사용하여 사용자 이름 `diag`과 구성한 일회용 암호를 이용해 Console 로컬 배포 VM에 연결합니다.

