---
sidebar: sidebar 
permalink: task-audit-console-activity.html 
keywords: administer, monitor, timeline, notifications, alerts, events, notification center, email, audit page, audit action 
summary: '감사 페이지에서 사용자 활동(UI 및 API에서 시작된 활동 모두 포함)을 감사하고 콘솔에서 수행하는 작업 상태를 모니터링하여 해결해야 할 문제가 있는지 확인할 수 있습니다. 감사 페이지에서 상태를 확인하거나 감사 로그를 자체 syslog 서버로 전송하도록 구성할 수 있습니다.' 
---
= NetApp Console 로컬 배포 활동 감사
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
감사 페이지에서 UI와 API를 통해 시작된 사용자 활동을 모두 감사할 수 있으며, NetApp Console 로컬 배포에서 작업 상태와 작업을 시작한 사용자를 모니터링할 수 있습니다.

.필수 역할
슈퍼 관리자, 조직 관리자, 폴더 및 플릿 관리자, 운영 지원 분석가, 슈퍼 뷰어, 조직 뷰어 또는 폴더 및 플릿 뷰어. link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보기"].

콘솔 로컬 배포에서 감사 활동을 확인하거나, 감사 로그를 CSV 파일로 다운로드하거나, 웹훅을 사용하여 감사 로그를 자체 syslog 서버로 전송하도록 구성할 수 있습니다.



[[audit-user-activity-from-the-audit-page]]
== Audit 페이지에서 사용자 활동 감사

감사 페이지를 사용하여 누가 작업을 수행했는지 또는 작업 상태를 확인할 수 있습니다.

감사 페이지에는 사용자가 조직 내에서 완료한 작업이 표시됩니다. 예를 들어, 누가 조직에 구성원을 추가했는지, 플릿이 성공적으로 삭제되었는지 등을 확인할 수 있으며, 사용자가 조직에서 수행한 다른 스토리지 관리 작업도 볼 수 있습니다.

감사 로그에는 다음 서비스에 대한 활동 내역이 표시됩니다.

* 테넌트 관리: 사용자 추가, 플릿 생성, 리소스 연결 등 조직 관리와 관련된 작업입니다.
* 스토리지 관리: 스토리지 리소스 관리와 관련된 작업입니다.
* 연합: 연합 생성, 연합 조직 추가 또는 제거 등 연합 관리와 관련된 작업입니다.


.단계
. *관리 > 감사*를 선택합니다.
. 표 위에 있는 필터를 사용하여 표에 표시되는 작업을 변경합니다.
+
예를 들어, *서비스* 필터를 사용하여 특정 서비스와 관련된 작업을 표시하거나, *사용자* 필터를 사용하여 특정 사용자 계정과 관련된 작업을 표시할 수 있습니다.





[[filter-audit-logs-for-identity-and-access-management-actions]]
=== ID 및 액세스 관리 작업에 대한 감사 로그 필터링

멤버 추가, 플릿 생성 또는 리소스 삭제 등 조직 관리와 관련된 작업만 보려면 Tenancy 서비스별로 감사 로그를 필터링하십시오.

.단계
. *관리 > 감사*를 선택합니다.
. 필터를 사용하여 결과를 좁힙니다. *서비스*를 선택한 다음 *테넌트*를 선택합니다.
. 다른 필터를 사용하여 결과를 더욱 세분화할 수 있습니다.
+
예를 들어, *사용자* 필터를 사용하여 특정 사용자 계정이 수행한 IAM 작업을 표시할 수 있습니다.





[[download-audit-logs-from-the-audit-page]]
=== 감사 페이지에서 감사 로그 다운로드

감사 페이지에서 감사 로그를 CSV 파일로 다운로드할 수 있습니다. 이를 통해 조직 내 사용자가 수행하는 작업의 기록을 유지할 수 있습니다. 다운로드한 CSV 파일에는 감사 페이지의 필터 설정이나 표시 열과 관계없이 모든 감사 로그 열이 포함됩니다.

.단계
. *감사* 페이지에서 표의 오른쪽 상단에 있는 다운로드 아이콘을 선택합니다.

