---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, directory user, directory users, service account, member, role, permissions, organization, fleet, folder, iam, identity and access management, access roles, add members, grant permissions, AD, Active Directory, directory services 
summary: 멤버를 추가하고 역할을 할당하여 조직의 리소스 계층 구조의 다양한 수준에 걸쳐 권한을 부여합니다. 
---
= NetApp Console 로컬 배포 조직에 구성원을 추가합니다.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console 로컬 배포 조직에 구성원을 추가하고 역할을 할당하여 사용자, 서비스 계정 및 디렉터리 사용자에 대해 조직, 폴더 또는 플릿 수준에서 액세스 권한을 부여할 수 있습니다.

.필수 액세스 역할
최고 관리자, 조직 관리자 또는 폴더/플릿 관리자(자신이 관리하는 폴더 및 플릿에 한함). link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보기"].



[[before-you-begin]]
== 시작하기 전에

* 조직에 맞는 폴더 및 플릿 계층 구조를 생성하십시오. link:task-iam-manage-folders-fleets.html["폴더와 플릿을 활용하여 리소스를 체계적으로 관리하는 방법을 알아보십시오."].
* 멤버 액세스 권한을 할당하기 전에 리소스를 올바른 플릿과 연결하십시오. link:task-iam-manage-resources.html["폴더와 플릿에서 리소스를 관리하는 방법을 알아보십시오."].
* 디렉터리 사용자를 추가하려면 먼저 디렉터리 서비스를 통합해야 합니다. link:task-iam-active-directory-integrate.html["디렉토리 서비스와 연동하는 방법을 알아보십시오."].




[[understand-how-access-is-granted-in-netapp-console-local-deployment]]
== NetApp Console 로컬 배포에서 액세스 권한이 부여되는 방식 이해

NetApp Console은 역할 기반 액세스 제어(RBAC)를 사용하여 권한을 관리합니다. 구성원에게 역할을 할당하여 필요한 액세스 권한을 부여하십시오. 각 역할은 특정 리소스에 대해 허용되는 작업을 정의합니다.

NetApp Console 로컬 배포에서 액세스 권한을 부여할 때 다음 사항에 유의하십시오.

* 사용자가 리소스에 액세스하려면 각 사용자를 조직에 명시적으로 추가하고 최소 하나 이상의 역할을 할당해야 합니다.
* 조직 또는 폴더 수준에서 할당한 역할은 하위 범위로 상속되므로, 구성원에게 필요한 곳에만 액세스 권한을 부여하려면 할당 범위를 신중하게 선택해야 합니다. link:concept-iam-rbac.html#role-inheritance["NetApp Console 로컬 배포에서 역할 상속에 대해 알아보십시오."].




[[add-members-to-your-organization]]
[[add-members]]
== 조직에 구성원 추가

NetApp Console은 사용자 계정, 디렉터리 사용자 및 서비스 계정의 세 가지 유형의 멤버를 지원합니다.


NOTE: 콘솔 로컬 배포에서 사용자를 추가하기 전에 먼저 이메일 서버를 구성해야 합니다.link:task-console-configure-notifications-delivery.html["이메일 서버 설정 방법을 알아보십시오."]

디렉터리 사용자는 통합 디렉터리 서비스를 통해 인증하지만, Console 로컬 배포에서 각 디렉터리 사용자를 개별적으로 추가하고 역할을 할당해야 합니다. 서비스 계정은 Console에서 직접 생성합니다.

콘솔 로컬 배포에 액세스하려면 모든 구성원에게 최소 하나 이상의 역할이 명시적으로 할당되어 있어야 합니다.

멤버를 추가할 때는 해당 멤버에게 액세스 권한이 필요한 조직, 폴더 또는 플릿을 선택하고 필요한 시작 역할을 할당하십시오.



[[add-a-user-account]]
=== 사용자 계정 추가

조직, 폴더 또는 플릿에 사용자를 추가하여 해당 리소스에 액세스할 수 있도록 하려면 조직 관리자, 폴더 또는 플릿 관리자 역할이 있어야 합니다.

.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *구성원*을 선택합니다.
. *멤버 추가*를 선택합니다.
. *구성원 유형*의 경우 *사용자*가 선택된 상태로 유지하십시오.
. *사용자 이메일*란에는 사용자가 생성한 로그인과 연결된 이메일 주소를 입력하십시오.
. *조직, 폴더 또는 플릿 선택* 섹션을 사용하여 구성원이 액세스해야 하는 위치를 선택하십시오.
+
다음 사항에 유의하십시오.

+
** 권한이 있는 폴더와 플릿만 선택할 수 있습니다.
** 조직이나 폴더를 선택하면 해당 구성원에게 모든 콘텐츠에 대한 권한이 부여됩니다.
** *조직 관리자* 역할은 조직 수준에서만 부여할 수 있습니다.


. *카테고리를 선택* 한 다음 선택한 조직, 폴더 또는 플릿에 필요한 시작 권한을 구성원에게 부여하는 *역할*을 선택합니다.
+
link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보기"].

. 더 많은 폴더, 플릿 또는 역할에 대한 액세스 권한을 부여하려면 *역할 추가*를 선택하고 폴더, 플릿 또는 역할 범주를 선택한 다음 역할을 선택하십시오.
. *추가*를 선택합니다.
+
콘솔은 사용자에게 이메일로 지침을 보냅니다.




NOTE: 로컬 사용자 초대 링크는 일회용이며 7일 후에 만료됩니다. 사용자가 설정을 완료하기 전에 링크가 만료된 경우, 해당 사용자를 삭제한 후 다시 추가하여 새 초대 링크를 보내십시오.



[[add-a-service-account]]
[[service-account]]
=== 서비스 계정 추가

작업을 자동화하거나 Console API에 안전하게 연결해야 할 때 서비스 계정을 추가합니다. 계정을 생성한 후, 해당 계정을 사용할 통합에 필요한 클라이언트 ID와 클라이언트 시크릿을 복사합니다.

.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *구성원*을 선택합니다.
. *멤버 추가*를 선택합니다.
. *구성원 유형*에서 *서비스 계정*을 선택합니다.
. 서비스 계정 이름을 입력합니다.
. *조직, 폴더 또는 플릿 선택* 섹션을 사용하여 서비스 계정에 액세스 권한이 필요한 위치를 선택하십시오.
+
다음 사항에 유의하십시오.

+
** 권한이 있는 폴더와 플릿에서만 선택할 수 있습니다.
** 조직 또는 폴더를 선택하면 해당 구성원에게 해당 콘텐츠의 모든 내용에 대한 권한이 부여됩니다.
** *조직 관리자* 역할은 조직 수준에서만 부여할 수 있습니다.


. * 범주 * 를 선택한 다음, 선택한 조직, 폴더 또는 플릿에 필요한 초기 권한을 서비스 계정에 부여하는 * 역할 * 을 선택하십시오.
+
link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보기"].

. 더 많은 폴더, 플릿 또는 역할에 대한 액세스 권한을 부여하려면 *역할 추가*를 선택하고 폴더, 플릿 또는 역할 범주를 선택한 다음 역할을 선택하십시오.
. 클라이언트 ID와 클라이언트 시크릿을 다운로드하거나 복사합니다.
+
Console에는 클라이언트 비밀 키가 한 번만 표시됩니다. 안전하게 복사해 두십시오. 분실하더라도 나중에 다시 생성할 수 있습니다.

. *닫기*를 선택합니다.




[[add-a-directory-user-to-your-organization]]
== 디렉터리 사용자를 조직에 추가합니다

통합 디렉터리 서비스에서 사용자를 추가하고 첫 번째 역할을 부여합니다. 예를 들어 Active Directory에서 새 스토리지 엔지니어를 추가하고 `Production-US-East` 플릿에 Storage admin 역할을 할당하여 해당 플릿에서 작업할 수 있도록 합니다.

디렉터리 사용자를 추가하기 전에 먼저 디렉터리 서비스를 구성해야 합니다. link:task-iam-active-directory-integrate.html["디렉토리 서비스와 연동하는 방법을 알아보십시오."].

.단계
. *관리 > ID 및 액세스*를 선택합니다.
. *구성원*을 선택합니다.
. *멤버 추가*를 선택합니다.
. *멤버 유형*에서 *디렉토리 사용자*를 선택하십시오.
. *사용자 이메일* 필드에는 추가하려는 디렉터리 사용자의 이메일 주소를 입력하십시오. 이 이메일 주소는 디렉터리에서 해당 사용자의 로그인과 연결된 이메일 주소와 일치해야 합니다.
. 디렉터리 사용자가 액세스해야 하는 위치를 선택하려면 *조직, 폴더 또는 그룹 선택* 섹션을 사용하십시오.
+
다음 사항에 유의하십시오.

+
** 권한이 있는 폴더와 플릿에서만 선택할 수 있습니다.
** 조직 또는 폴더를 선택하면 해당 구성원에게 해당 콘텐츠의 모든 내용에 대한 권한이 부여됩니다.
** *조직 관리자* 역할은 조직 수준에서만 부여할 수 있습니다.


. * 범주 * 를 선택한 다음, 선택한 조직, 폴더 또는 플릿에 필요한 초기 권한을 디렉터리 사용자에게 부여하는 * 역할 * 을 선택하십시오.
+
link:reference-iam-predefined-roles.html["액세스 역할에 대해 알아보기"].

. 사용자에게 다른 폴더, 플릿 또는 역할에 대한 추가 액세스 권한을 부여하려면 *역할 추가*를 선택하고 폴더 또는 플릿, 역할 범주를 선택한 다음 역할을 선택합니다.

