= 
:allow-uri-read: 


전용 호스트:: 콘솔 에이전트는 다른 애플리케이션과 공유하는 호스트에서는 지원되지 않습니다. 호스트는 전용 호스트여야 합니다. 호스트는 다음 크기 요구 사항을 충족하는 모든 아키텍처를 사용할 수 있습니다.
+
--
* CPU: 8코어 또는 8개의 vCPU
* RAM: 32 GB
* 디스크 공간: 호스트에는 165GB가 권장되며, 파티션 요구 사항은 다음과 같습니다.
+
** `/opt`: 120GiB의 여유 공간이 필요합니다.
+
에이전트는  `/opt`을 사용하여  `/opt/application/netapp` 디렉터리와 그 내용을 설치합니다.

** `/var`: 40GiB의 여유 공간이 필요합니다.
+
콘솔 에이전트는 Docker 또는 Podman이 이 디렉터리 내에 컨테이너를 생성하도록 설계되었기 때문에 `/var` 이 공간이 필요합니다. 구체적으로, 컨테이너는 `/var/lib/containers/storage` 디렉터리에 생성됩니다. 외부 마운트 또는 심볼릭 링크는 이 공간에서 작동하지 않습니다.





--


* CPU: 16코어 또는 16개의 vCPU
* RAM: 64 GB
* 디스크 공간: 596GB (씩 프로비저닝 권장)
* vSphere 7.0u3 이상, 가상 하드웨어 버전 19 이상


[NOTE]
====
* ESXi 호스트에서는 VM이 시작될 때 CPU와 메모리가 할당되는 것이 아니라 예약됩니다. 대상 호스트에 최소 16개의 CPU 코어와 64GB를 예약되지 않은 용량으로 사용할 수 있는지 확인하십시오. 호스트에 기존 VM 예약이 있으면 사용 가능한 용량이 줄어듭니다.
* 데이터 저장소는 최소 디스크 쓰기 성능 요건을 충족해야 합니다. fsync p99 쓰기 지연 시간은 20ms 이하, 4K 랜덤 쓰기 IOPS는 200 이상이어야 합니다. 지연 시간이 50ms를 초과하거나 IOPS가 30 미만이면 배포가 실패합니다.
* IPv6는 지원되지 않습니다. 고정 IPv4 주소가 필요합니다.
* ESXi 호스트에 직접 설치하는 대신 vCenter 환경에 NetApp Console 로컬 배포를 설치하십시오.


====

NOTE: 콘솔 에이전트는 UID 및 GID 범위 19000~19200을 예약합니다. 이 범위는 고정되어 있으며 수정할 수 없습니다. 호스트에서 타사 소프트웨어가 이 범위 내의 UID 또는 GID를 사용하는 경우 에이전트 설치가 실패합니다. NetApp은 충돌을 방지하기 위해 타사 소프트웨어가 없는 호스트를 사용할 것을 권장합니다.

NetApp Console 로컬 배포는 서비스 간 통신을 위해 고정 주소 공간을 사용합니다. 내부 네트워크에는 10.42.0.0/16 및 10.43.0.0/16 IP 범위가 사용됩니다. Console 로컬 배포를 설치하기 전에 Console 로컬 배포에 할당된 VLAN에서 이러한 IP 범위가 다른 VM, DHCP 범위, DNS 레코드 또는 로드 밸런서 VIP 풀에 할당되지 않았는지 확인하십시오.

에이전트 인터페이스의 IP 주소를 변경하는 방법에 대한 지침은 기술 자료 문서 "Agent IP conflict with existing network"를 참조하십시오.

하이퍼바이저:: 지원되는 운영 체제를 실행할 수 있도록 인증된 베어메탈 또는 호스팅 하이퍼바이저가 필요합니다.


[[podman-versions]]운영 체제 및 컨테이너 요구 사항:: 콘솔 에이전트는 표준 모드 또는 제한된 모드에서 Console을 사용할 때 다음 운영 체제에서 지원됩니다. 에이전트를 설치하기 전에 컨테이너 오케스트레이션 툴이 필요합니다.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| 운영 체제 | 지원되는 OS 버전 | 지원되는 에이전트 버전 | 필수 컨테이너 툴 | SELinux 


 a| 
Red Hat Enterprise Linux
 a| 
9.1~9.4

8.6~8.10

* 영어 버전만 제공됩니다.
* 호스트는 Red Hat Subscription Management에 등록되어 있어야 합니다. 등록되어 있지 않으면 에이전트 설치 중에 필요한 타사 소프트웨어를 업데이트하기 위한 저장소에 액세스할 수 없습니다.

 a| 
3.9.50 이상(콘솔이 표준 모드 또는 제한된 모드인 경우)
 a| 
Podman 버전 4.6.1 또는 4.9.4

<<podman-configuration,Podman 구성 요구 사항 보기>>.
 a| 
강제 모드 또는 허용 모드에서 지원됩니다

* 운영 체제에서 SELinux가 활성화된 에이전트는 Cloud Volumes ONTAP 시스템 관리를 지원하지 않습니다.




 a| 
Ubuntu
 a| 
24.04 LTS
 a| 
표준 모드 또는 제한된 모드의 NetApp Console이 포함된 3.9.45 이상
 a| 
Docker Engine 23.06 ~ 28.0.0.
 a| 
지원되지 않음



 a| 
22.04 LTS
 a| 
3.9.50 이상
 a| 
Docker Engine 23.0.6 ~ 28.0.0.
 a| 
지원되지 않음

|===
--


[[podman-versions]]운영 체제 및 컨테이너 요구 사항:: 콘솔 에이전트는 개인 모드에서 콘솔을 사용할 때 다음 운영 체제를 지원합니다. 에이전트를 설치하기 전에 컨테이너 오케스트레이션 툴이 필요합니다.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| 운영 체제 | 지원되는 OS 버전 | 지원되는 에이전트 버전 | 필수 컨테이너 툴 | SELinux 


 a| 
Red Hat Enterprise Linux
 a| 
9.1~9.4

8.6~8.10
 a| 
콘솔을 비공개 모드로 실행하고 버전 3.9.42 이상이어야 합니다.
 a| 
Podman 버전 4.6.1 또는 4.9.4

<<podman-configuration,Podman 구성 요구 사항 보기>>.
 a| 
강제 모드 또는 허용 모드에서 지원됩니다^1^



 a| 
Ubuntu
 a| 
22.04 LTS
 a| 
3.9.29 이상
 a| 
Docker Engine 23.0.6 ~ 26.0.0

26.0.0 버전은 _new_ 에이전트 3.9.44 이상 설치에서 지원됩니다.
 a| 
지원되지 않음

|===
참고:

. Cloud Volumes ONTAP 시스템 관리는 운영 체제에서 SELinux가 활성화된 에이전트에서는 지원되지 않습니다.
. 콘솔 에이전트는 이러한 운영 체제의 영어 버전에서 지원됩니다.
. RHEL의 경우 호스트가 Red Hat Subscription Management에 등록되어 있어야 합니다. 등록되어 있지 않으면 호스트는 에이전트 설치 중에 필요한 타사 소프트웨어를 업데이트하기 위한 저장소에 액세스할 수 없습니다.


--


CPU:: 8코어 또는 8개의 vCPU
RAM:: 32 GB


AWS EC2 인스턴스 유형:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. t3.2xlarge를 권장합니다.


키 페어:: 콘솔 에이전트를 생성할 때 인스턴스와 함께 사용할 EC2 키 페어를 선택해야 합니다.


IMDSv2 사용 시 PUT 응답 홉 제한:: EC2 인스턴스에서 IMDSv2가 활성화된 경우(새 EC2 인스턴스의 기본 설정임), 인스턴스의 PUT 응답 홉 제한을 3으로 변경해야 합니다. EC2 인스턴스에서 이 제한을 변경하지 않으면 에이전트를 설정하려고 할 때 UI 초기화 오류가 발생합니다.
+
--
* link:task-require-imdsv2.html["Amazon EC2 인스턴스에서 IMDSv2 사용을 필수로 지정합니다."]
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-existing-instances.html#modify-PUT-response-hop-limit["AWS 문서: PUT 응답 홉 제한 변경"^]


--


Azure VM 크기:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. Standard_D8s_v3을 권장합니다.


Google Cloud 머신 유형:: 위의 CPU 및 RAM 요구 사항을 충족하는 인스턴스 유형입니다. n2-standard-8을 권장합니다.
+
--
콘솔 에이전트는 지원되는 OS가 설치된 VM 인스턴스의 Google Cloud에서 지원됩니다. https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["보호된 VM 기능"^]

--


/opt의 디스크 공간:: 100GiB의 여유 공간이 필요합니다.
+
--
에이전트는  `/opt`을 사용하여  `/opt/application/netapp` 디렉터리와 그 내용을 설치합니다.

--
/var의 디스크 공간:: 20GiB의 여유 공간이 필요합니다.
+
--
콘솔 에이전트는 Docker 또는 Podman이 이 디렉터리 내에 컨테이너를 생성하도록 설계되었기 때문에 `/var` 이 공간이 필요합니다. 구체적으로, 컨테이너는 `/var/lib/containers/storage` 디렉터리에 생성됩니다. 외부 마운트 또는 심볼릭 링크는 이 공간에서 작동하지 않습니다.

--

